/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz_Admin;
import Gestion.GestionReportes1;
import Personas.*;
import Vehiculos.*;
import Ventas.*;
import Promociones.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author sebas
 */
public class GestionCotizaciones extends javax.swing.JFrame {

    /**
     * Creates new form GestionCotizaciones
     */
    public GestionCotizaciones() {
        initComponents();
    this.setTitle("Gestión de Cotizaciones");
    this.setLocationRelativeTo(null);

    this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    configurarTabla();
    llenarCombos();
    listarCotizaciones();
    }
    private void configurarTabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Cód.");
        modelo.addColumn("Cliente");
        modelo.addColumn("Vehículo");
        modelo.addColumn("Precio Base");
        modelo.addColumn("Descuento");
        modelo.addColumn("Total");
        modelo.addColumn("Estado");
        
        tblCotizaciones.setModel(modelo);
    }
    private void llenarCombos() {
        // Limpiamos primero
        cboCliente.removeAllItems();
        cboVendedor.removeAllItems();
        cboVehiculo.removeAllItems();
        cboPromocion.removeAllItems();

        // 1. Clientes
        for (int i = 0; i < GestionReportes1.getContClientes(); i++) {
            cboCliente.addItem(GestionReportes1.getListaClientes()[i]);
        }

        // 2. Vendedores (Solo empleados con rol VENDEDOR)
        for (int i = 0; i < GestionReportes1.getContEmpleados(); i++) {
            Empleado emp = GestionReportes1.getListaEmpleados()[i];
            if (emp.esVendedor()) { 
                cboVendedor.addItem((Vendedor) emp);
            }
        }

        // 3. Vehículos (Solo los DISPONIBLES)
        for (int i = 0; i < GestionReportes1.getContVehiculos(); i++) {
            Vehiculo v = GestionReportes1.getListaVehiculos()[i];
            if (v.getEstado() == EstadoVehiculo.DISPONIBLE) {
                cboVehiculo.addItem(v);
            }
        }

        // 4. Promociones
        cboPromocion.addItem("Sin Promoción"); 
        for (int i = 0; i < GestionReportes1.getContPromociones(); i++) {
            cboPromocion.addItem(GestionReportes1.getListaPromociones()[i]);
        }
    }

    private void listarCotizaciones() {
        DefaultTableModel modelo = (DefaultTableModel) tblCotizaciones.getModel();
        modelo.setRowCount(0); // Limpiar tabla

        for (int i = 0; i < GestionReportes1.getContCotizaciones(); i++) {
            Cotizacion c = GestionReportes1.getListaCotizaciones()[i];
            
            Object[] fila = {
                c.getCodigo(),
                c.getCliente().getNombres(),
                c.getVehiculo().getMarca() + " " + c.getVehiculo().getModelo(),
                c.getPrecioBase(),
                c.getDescuento(),
                c.getTotal(),
                c.getEstado()
            };
            modelo.addRow(fila);
        }
    }

        
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCotizaciones = new javax.swing.JTable();
        btnGenerar = new javax.swing.JButton();
        jblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        cboCliente = new javax.swing.JComboBox<>();
        cboVendedor = new javax.swing.JComboBox<>();
        cboVehiculo = new javax.swing.JComboBox<>();
        cboPromocion = new javax.swing.JComboBox<>();
        lblResultado = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblCotizaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblCotizaciones);

        btnGenerar.setText("Generar Cotizacion");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        jblCodigo.setText("Digite el codigo :");

        cboCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboVendedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboPromocion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblResultado.setText("Total");

        txtResultado.setText("jTextField1");
        txtResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jblCodigo)
                        .addGap(47, 47, 47)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cboPromocion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addComponent(cboVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGenerar)
                            .addComponent(cboVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(cboPromocion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnGenerar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResultado)
                    .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed

        
        
        if (txtCodigo.getText().trim().isEmpty() || 
            cboCliente.getSelectedItem() == null || 
            cboVendedor.getSelectedItem() == null || 
            cboVehiculo.getSelectedItem() == null) {
            
            JOptionPane.showMessageDialog(this, "Por favor complete todos los datos.");
            return;
        }

        try {
            // 2. Obtener datos seleccionados
            String codigo = txtCodigo.getText().trim();
            Cliente cliente = (Cliente) cboCliente.getSelectedItem();
            Vendedor vendedor = (Vendedor) cboVendedor.getSelectedItem();
            Vehiculo vehiculo = (Vehiculo) cboVehiculo.getSelectedItem();
            
            // 3. Verificar Promoción
            Promocion promo = null;
            Object itemPromo = cboPromocion.getSelectedItem();
            if (itemPromo instanceof Promocion) {
                promo = (Promocion) itemPromo;
            }

            // 4. Crear Cotización (La clase hace el cálculo sola)
            Cotizacion nuevaCoti = new Cotizacion(codigo, cliente, vendedor, vehiculo, promo);

            // 5. Guardar
            GestionReportes1.agregarCotizaciones(nuevaCoti);

            // 6. Actualizar pantalla
            listarCotizaciones();
            lblResultado.setText("Total: S/ " + nuevaCoti.getTotal());
            
            JOptionPane.showMessageDialog(this, "¡Cotización generada exitosamente!");
            txtCodigo.setText(""); // Limpiar código

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al generar: " + e.getMessage());
        }
       
      

    }//GEN-LAST:event_btnGenerarActionPerformed

    private void txtResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoActionPerformed
       lblResultado.setText("Total: S/0.00");
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionCotizaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionCotizaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionCotizaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionCotizaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionCotizaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JComboBox<Object> cboCliente;
    private javax.swing.JComboBox<Object> cboPromocion;
    private javax.swing.JComboBox<Object> cboVehiculo;
    private javax.swing.JComboBox<Object> cboVendedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jblCodigo;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTable tblCotizaciones;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}

