/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz_Admin;

import Gestion.GestionReportes1;
import Personas.Empleado;
import java.awt.SystemColor;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
/**
 *
 * @author Leonardo
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public login() {
        initComponents();
    getContentPane().setBackground(SystemColor.activeCaption);
    setLocationRelativeTo(null);

    jbSalir.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbSalirActionPerformed(evt);
        }
    });

    jbIngresar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbIgresarActionPerformed(evt);
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuariotxt = new javax.swing.JLabel();
        jbSalir = new javax.swing.JButton();
        contratxt = new javax.swing.JLabel();
        jbIngresar = new javax.swing.JButton();
        logintxt = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        lblImagen = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usuariotxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usuariotxt.setText("Usuario: ");

        jbSalir.setText("Salir");

        contratxt.setText("Contraseña:");

        jbIngresar.setText("Ingresar");
        jbIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIngresarActionPerformed(evt);
            }
        });

        logintxt.setBackground(new java.awt.Color(255, 255, 255));
        logintxt.setFont(new java.awt.Font("Gadugi", 1, 48)); // NOI18N
        logintxt.setForeground(new java.awt.Color(0, 102, 204));
        logintxt.setText("Consesionaria DreamCars");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contratxt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usuariotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(376, 376, 376))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jbIngresar)
                                        .addGap(173, 173, 173)))
                                .addComponent(jbSalir))
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(logintxt)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(300, 300, 300)
                    .addComponent(lblImagen)
                    .addContainerGap(471, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(logintxt, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuariotxt)
                    .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contratxt)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbIngresar)
                    .addComponent(jbSalir))
                .addGap(47, 47, 47))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(128, 128, 128)
                    .addComponent(lblImagen)
                    .addContainerGap(228, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIngresarActionPerformed
 
        


    }//GEN-LAST:event_jbIngresarActionPerformed
    
   private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {                                        
    dispose();  // cierra la ventana de login
}                                       

private void jbIgresarActionPerformed(java.awt.event.ActionEvent evt) {                                           
   if (txtNombre1.getText().trim().equals("")) {
        mensaje("Ingrese el usuario");
        txtNombre1.requestFocus();
        return;
    }

    // Obtener la contraseña del PasswordField
    String desClave = String.valueOf(jPasswordField1.getPassword()).trim();
    String desUsuario = txtNombre1.getText().trim();

    if (desClave.equals("")) {
        mensaje("Ingrese la contraseña");
        jPasswordField1.requestFocus();
        return;
    }

    // Buscar empleado registrado
    Empleado empleadoEncontrado = GestionReportes1.buscarEmpleado(desUsuario, desClave);

    if (empleadoEncontrado != null) {
        ingresarAlSistema(empleadoEncontrado);

    } else if (desUsuario.equals("admin") && desClave.equals("loco")) {
        // ADMIN HARDCODEADO
        Personas.Administrador superAdmin = new Personas.Administrador(
            "00000000", "Super", "Admin", "", "", "", "", "admin", "loco"
        );
        ingresarAlSistema(superAdmin);

    } else if (desUsuario.equals("vend") && desClave.equals("12345")) {
        // VENDEDOR HARDCODEADO
        Empleado vendedorDemo = new Empleado(
            "11111111",
            "Vendedor",
            "Demo",
            "",
            "",
            "",
            "",
            "vend",
            "12345",
            "VENDEDOR"
        );
        ingresarAlSistema(vendedorDemo);

    } else {
        mensaje("Usuario o contraseña incorrectos.");
    }

    
}
private void ingresarAlSistema(Empleado emp){
    MenuPrincipal menu =new MenuPrincipal(emp);
    menu.setVisible(true);
    this.dispose();
}







  private void mensaje(String cadena) {
    JOptionPane.showMessageDialog(this, cadena);
  }

    /**
     * @param args the command line arguments
     */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        // Opcional: Look and Feel de Windows
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) { }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contratxt;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton jbIngresar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel logintxt;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JLabel usuariotxt;
    // End of variables declaration//GEN-END:variables
}
